# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@root" "ssd" "compress-force=zstd:1" "noatime" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/f1c791fb-2e5d-410c-962b-fe4654f7ec78";

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@var_lib_machines" "ssd" "compress-force=zstd:1" "noatime" ];
    };

  fileSystems."/var/lib/portables" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@var_lib_portables" "ssd" "compress-force=zstd:1" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@var_log" "ssd" "compress-force=zstd:1" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/.swap" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@nix" "ssd" "compress-force=zstd:1" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@persist" "ssd" "compress-force=zstd:1" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/34DD-1655";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a7b63feb-1869-4982-abea-474db999ff46";
      fsType = "btrfs";
      options = [ "subvol=@home" "ssd" "compress-force=zstd:1" "noatime" ];
    };

  swapDevices = [{
	device = "/.swap/swapfile";
	size = 24 * 1024;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
